server:
  port: 5000
  servlet:
    context-path: /
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

spring:
  application:
    name: BrokerWallet Backend
  
  # 输出编码配置
  output:
    ansi:
      enabled: detect
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/brokerwallet?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Wan05609  # 请根据您的MySQL配置修改密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update  # 自动创建/更新表结构
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
  
  # 区块链配置（从根目录配置文件加载）
  config:
    import: "file:./blockchain-config.yml"

# 区块链配置
blockchain:
  rpc-url: "http://127.0.0.1:8545"
  account-address: "0x8c056ccb92c567da3fee27c23d4f2f107f203879"
  contracts:
    medal-contract: "0x1a202bfa10ea97a742ad22fcb1a7913821bf1b18"
    nft-contract: "0x382ca68b8133893fdf46170efd839c7703d9e9ae"

# 自定义配置
brokerwallet:
  # 服务器URL配置（用于图片访问）
  server:
    # USB连接调试时使用本地IP，部署到云服务器时修改为云服务器地址
    # 例如：http://192.168.1.100:5000 或 http://your-domain.com
    url: "http://localhost:5000"
  
  file:
    # 文件存储路径（相对于项目根目录）
    upload-path: uploads/
    # 允许的文件类型
    allowed-types: 
      - image/jpeg
      - image/png
      - image/gif
      - application/pdf
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - text/plain
    # 最大文件大小（字节）
    max-size: 52428800  # 50MB

# 缓存配置
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m  # 最大1000条记录，5分钟过期
    cache-names:
      - medal-ranking      # 勋章排行榜缓存
      - user-statistics    # 用户统计信息缓存
      - proof-statistics   # 证明文件统计缓存

# 日志配置
logging:
  level:
    com.brokerwallet: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cache: DEBUG  # 缓存日志
    org.web3j: INFO  # Web3j日志级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8
    file: UTF-8
  file:
    name: logs/brokerwallet-backend.log


